import type { Mentor } from "./types";

// Helper function to generate reviews
const generateReviews = (count: number = 3) => {
  return Array.from({ length: count }, (_, i) => ({
    id: `review-${i + 1}`,
    author: `Mentee ${i + 1}`,
    rating: 4 + Math.random(),
    date: new Date(Date.now() - Math.random() * 10000000000).toLocaleDateString(),
    content: "Great mentoring session! Learned a lot about system design and best practices.",
    authorImage: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`
  }));
};

// Helper function to generate resources
const generateResources = (specialty: string) => [
  {
    id: "res-1",
    title: `Essential ${specialty} Course`,
    type: "video" as const,
    url: "https://youtube.com",
    description: `Comprehensive guide to ${specialty} fundamentals and advanced concepts.`
  },
  {
    id: "res-2",
    title: `${specialty} Best Practices`,
    type: "article" as const,
    url: "https://medium.com",
    description: `Learn industry best practices for ${specialty} development.`
  }
];

// Helper function to generate career history
const generateCareerHistory = (company: string, role: string) => [
  {
    role,
    company,
    duration: "2020 - Present",
    description: "Leading technical initiatives and mentoring junior developers.",
    current: true
  },
  {
    role: `Senior ${role}`,
    company: "Previous Tech Corp",
    duration: "2018 - 2020",
    description: "Developed scalable solutions and improved system performance.",
    current: false
  }
];

export const mentorsData: Mentor[] = [
  // Engineering Category
  {
    id: 1,
    name: "Priya Sharma",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Senior Frontend Engineer",
    company: "Google",
    rating: 4.9,
    category: "engineering",
    subcategory: "frontend",
    skills: ["React", "TypeScript", "Next.js", "Performance Optimization", "Web Accessibility"],
    description: "Frontend specialist with expertise in React and modern web technologies.",
    availability: ["Monday Wednesday Friday", "9:00 AM - 5:00 PM"],
    sessionRate: "₹1999/hour",
    languages: ["English", "Hindi"],
    experience: "8+ years",
    linkedin: "https://linkedin.com/in/priyasharma",
    website: "https://priyasharma.dev",
    email: "priya.s@example.com",
    specializations: ["Frontend Architecture", "Performance", "Accessibility"],
    achievements: ["Led Google's frontend team", "Created accessibility guidelines", "Tech conference speaker"],
    location: "Bangalore, India",
    careerHistory: generateCareerHistory("Google", "Senior Frontend Engineer"),
    reviews: generateReviews(),
    resources: generateResources("Frontend Development"),
    minutesMentored: 1234,
    totalMentees: 89
  },
  {
    id: 2,
    name: "Arjun Patel",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Backend Engineer",
    company: "Amazon",
    rating: 4.8,
    category: "engineering",
    subcategory: "backend",
    skills: ["Node.js", "Python", "AWS", "Microservices", "System Design"],
    description: "Experienced backend developer specializing in scalable architectures.",
    availability: ["Tuesday Thursday", "10:00 AM - 6:00 PM"],
    sessionRate: "₹2499/hour",
    languages: ["English", "Hindi", "Gujarati"],
    experience: "10+ years",
    linkedin: "https://linkedin.com/in/arjunpatel",
    website: "https://arjunpatel.dev",
    email: "arjun.p@example.com",
    specializations: ["Distributed Systems", "Cloud Architecture", "API Design"],
    achievements: ["Built Amazon's payment processing system", "AWS certified architect", "Tech blogger"],
    location: "Mumbai, India",
    careerHistory: generateCareerHistory("Amazon", "Senior Backend Engineer"),
    reviews: generateReviews(),
    resources: generateResources("Backend Development"),
    minutesMentored: 2156,
    totalMentees: 124
  },

  // Data Science Category
  {
    id: 3,
    name: "Anjali Desai",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Data Scientist",
    company: "Netflix",
    rating: 4.9,
    category: "data-science",
    subcategory: "data-scientist",
    skills: ["Python", "Machine Learning", "Deep Learning", "Statistics", "Data Visualization"],
    description: "Data scientist with expertise in recommendation systems and predictive modeling.",
    availability: ["Monday Wednesday Friday", "11:00 AM - 7:00 PM"],
    sessionRate: "₹2999/hour",
    languages: ["English", "Hindi", "Marathi"],
    experience: "7+ years",
    linkedin: "https://linkedin.com/in/anjalidesai",
    website: "https://anjalidesai.ai",
    email: "anjali.d@example.com",
    specializations: ["Recommendation Systems", "NLP", "Computer Vision"],
    achievements: ["Led Netflix's content recommendation team", "Published ML research papers", "Kaggle competition winner"],
    location: "Pune, India",
    careerHistory: generateCareerHistory("Netflix", "Senior Data Scientist"),
    reviews: generateReviews(),
    resources: generateResources("Data Science"),
    minutesMentored: 1876,
    totalMentees: 98
  },
  {
    id: 4,
    name: "Rahul Kumar",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "ML Engineer",
    company: "Microsoft",
    rating: 4.7,
    category: "data-science",
    subcategory: "ai-ml",
    skills: ["TensorFlow", "PyTorch", "MLOps", "Computer Vision", "NLP"],
    description: "Machine learning engineer focused on deploying ML models at scale.",
    availability: ["Tuesday Thursday", "9:00 AM - 5:00 PM"],
    sessionRate: "₹2499/hour",
    languages: ["English", "Hindi"],
    experience: "6+ years",
    linkedin: "https://linkedin.com/in/rahulkumar",
    website: "https://rahulkumar.ai",
    email: "rahul.k@example.com",
    specializations: ["MLOps", "Model Optimization", "Edge AI"],
    achievements: ["Built Microsoft's computer vision platform", "Multiple patents in AI", "Tech conference speaker"],
    location: "Hyderabad, India",
    careerHistory: generateCareerHistory("Microsoft", "Senior ML Engineer"),
    reviews: generateReviews(),
    resources: generateResources("Machine Learning"),
    minutesMentored: 1543,
    totalMentees: 76
  },

  // Business Category
  {
    id: 5,
    name: "Neha Verma",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Marketing Director",
    company: "Meta",
    rating: 4.8,
    category: "business",
    subcategory: "marketing",
    skills: ["Digital Marketing", "Brand Strategy", "Growth Marketing", "Analytics", "Social Media"],
    description: "Marketing expert specializing in digital transformation and brand building.",
    availability: ["Monday Wednesday Friday", "10:00 AM - 6:00 PM"],
    sessionRate: "₹1999/hour",
    languages: ["English", "Hindi", "Bengali"],
    experience: "12+ years",
    linkedin: "https://linkedin.com/in/nehaverma",
    website: "https://nehaverma.marketing",
    email: "neha.v@example.com",
    specializations: ["Digital Strategy", "Brand Development", "Marketing Analytics"],
    achievements: ["Led Meta's global marketing campaigns", "Marketing Excellence Award", "Industry speaker"],
    location: "Delhi, India",
    careerHistory: generateCareerHistory("Meta", "Marketing Director"),
    reviews: generateReviews(),
    resources: generateResources("Digital Marketing"),
    minutesMentored: 2345,
    totalMentees: 156
  },
  {
    id: 6,
    name: "Vikram Singh",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Sales Director",
    company: "Salesforce",
    rating: 4.9,
    category: "business",
    subcategory: "sales",
    skills: ["B2B Sales", "Sales Strategy", "Account Management", "Negotiation", "CRM"],
    description: "Sales leader with expertise in enterprise software sales and team management.",
    availability: ["Tuesday Thursday", "11:00 AM - 7:00 PM"],
    sessionRate: "₹2499/hour",
    languages: ["English", "Hindi", "Punjabi"],
    experience: "15+ years",
    linkedin: "https://linkedin.com/in/vikramsingh",
    website: "https://vikramsingh.sales",
    email: "vikram.s@example.com",
    specializations: ["Enterprise Sales", "Team Leadership", "Sales Operations"],
    achievements: ["Top sales performer at Salesforce", "Built ₹100Cr+ sales pipeline", "Sales leadership awards"],
    location: "Gurgaon, India",
    careerHistory: generateCareerHistory("Salesforce", "Sales Director"),
    reviews: generateReviews(),
    resources: generateResources("Sales Strategy"),
    minutesMentored: 1987,
    totalMentees: 112
  },

  // Design Category
  {
    id: 7,
    name: "Aisha Reddy",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "Product Designer",
    company: "Airbnb",
    rating: 4.9,
    category: "design",
    subcategory: "ui-ux",
    skills: ["UI Design", "UX Research", "Design Systems", "Figma", "Prototyping"],
    description: "Product designer passionate about creating delightful user experiences.",
    availability: ["Monday Wednesday Friday", "9:00 AM - 5:00 PM"],
    sessionRate: "₹1999/hour",
    languages: ["English", "Hindi", "Telugu"],
    experience: "8+ years",
    linkedin: "https://linkedin.com/in/aishareddy",
    website: "https://aishareddy.design",
    email: "aisha.r@example.com",
    specializations: ["Design Systems", "Mobile Design", "User Research"],
    achievements: ["Redesigned Airbnb's mobile app", "Design conference speaker", "Design awards winner"],
    location: "Chennai, India",
    careerHistory: generateCareerHistory("Airbnb", "Senior Product Designer"),
    reviews: generateReviews(),
    resources: generateResources("Product Design"),
    minutesMentored: 1654,
    totalMentees: 87
  },
  {
    id: 8,
    name: "Karthik Iyer",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&h=200&auto=format&fit=crop",
    profession: "UX Researcher",
    company: "Apple",
    rating: 4.8,
    category: "design",
    subcategory: "ux-researcher",
    skills: ["User Research", "Usability Testing", "Data Analysis", "Workshop Facilitation", "Journey Mapping"],
    description: "UX researcher specializing in user behavior and product strategy.",
    availability: ["Tuesday Thursday", "10:00 AM - 6:00 PM"],
    sessionRate: "₹2499/hour",
    languages: ["English", "Hindi", "Tamil"],
    experience: "9+ years",
    linkedin: "https://linkedin.com/in/karthikiyer",
    website: "https://karthikiyer.research",
    email: "karthik.i@example.com",
    specializations: ["Behavioral Research", "Product Strategy", "User Psychology"],
    achievements: ["Led Apple's user research initiatives", "Published UX research papers", "Industry speaker"],
    location: "Bangalore, India",
    careerHistory: generateCareerHistory("Apple", "Senior UX Researcher"),
    reviews: generateReviews(),
    resources: generateResources("UX Research"),
    minutesMentored: 1432,
    totalMentees: 65
  }
];